### ISSUE TITLE
Add VR/XR support

### ISSUE THREAD

**Issue by schulzch** [UniStuttgart-VISUS/visual-system-simulator#2]
For research and publicity reasons, we want support for VR/XR devices that support Eye Tracking (e.g. [Varjo XR-1](https://developer.varjo.com/docs/native/varjo-native-sdk) and [Vive Pro Eye](https://vr.tobii.com/sdk/develop/unity/getting-started/vive-pro-eye/)).

While Tobii and Varjo promised to work on eye tracking extensions for OpenXR, we have no access yet. Thus, we might favor a native SDK, at least for eye tracking.

- [x] Gaze (input)
- [x] Fetch head and eye transforms from HMD
- [x] HMD swap chain integration
- [x] Use head and eye transform

**Comment by schulzch** [comment]
WGPU seems like a dead end for now, since we cannot punch through its abstraction to obtain texture handles (see https://github.com/gfx-rs/wgpu-rs/issues/538#issuecomment-683853122 ).

Publicity-wise, it might be worth doing a [Unity Native Plugin](https://docs.unity3d.com/Manual/NativePluginInterface.html).

**Comment by schulzch** [comment]
Currently, the Varjo XR-1 Unity plugin requires Unity's HRDP pipeline, which [has no support for OpenGL](https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@8.2/manual/System-Requirements.html). However, there is support for DirectX11 in `gfx-rs` with native access to texture handles (`view_texture_as_shader_resource_raw`).

**Comment by schulzch** [comment]
Another option for sharing textures would be [Spout](https://github.com/leadedge/Spout2), and possibly a C# wrapper for easy integration with Unity [KlakSpout](https://github.com/keijiro/KlakSpout).

**Comment by Link250** [comment]
When using the Native Varjo SDK the "Varjo_layers.h" header contains the neccesary API calls to create and manage the texture handles which need to be rendered into.
The Benchmark Example shows how to use these API calls in the IRenderer class and how to use the resulting texture handles in the RenderTarget class.

The Frame Info is used for per-frame view and projection matrices and can be retreived by calling `varjo_CreateFrameInfo(session)`. An example can be found in the "main.cpp" file.

Gaze-Tracking data can be retrieved by calling `varjo_GetGaze(session)` after setting it up (full example in the GazeTracking class of the Benchmark Example).

**Comment by Link250** [comment]
Example for a Unity Native Plugin getting a texture handle from Unity and rendering into it:
https://github.com/Unity-Technologies/NativeRenderingPlugin

**Comment by schulzch** [comment]
I'll leave this open until OpenXR works fully too.

**Comment by schulzch** [comment]
Closing since we have working Varjo support and OpenXR is big enough to be a separate task.
